# mango-api/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate --schema=./prisma/schema

EXPOSE 3000

CMD ["npm", "run", "start:dev"]